### ISSUE TITLE
CXuesong.JsonRpc.AspNetCore nuget package needs update

### ISSUE THREAD

**Issue by mikedld** [CXuesong/JsonRpc.Standard#11]
Currently available CXuesong.JsonRpc.AspNetCore package version 0.4.3 still depends on CXuesong.JsonRpc.Standard while other packages have been bumped to 0.5.0+ which had it renamed to CXuesong.JsonRpc.Commons. This results in issues such as still having to use types in the old namespace (e.g. `JsonRpc.Standard.Server.JsonRpcService`), or `JsonRpc.Standard.Server.JsonRpcServiceHost` failing to catch exceptions of type `JsonRpc.Server.JsonRpcException`, unless one switches to a pre-0.5.0 version for all the other dependencies.

**Comment by CXuesong** [comment]
Oops. I must have missed to upload `JsonRpc.AspNetCore` package onto NuGet. I've picked the package from [`v0.5.0`](https://github.com/CXuesong/JsonRpc.Standard/releases/tag/v0.5.0) and [uploaded it](https://www.nuget.org/packages/CXuesong.JsonRpc.AspNetCore/0.5.0) just now. You may update your package dependency in a while.

Note you may also need to remove reference `CXuesong.JsonRpc.Standard` manually if you have added it explicitly in your project.

**Comment by mikedld** [comment]
Looks good, thanks ;)
