### ISSUE TITLE
Unable to get AspNetCore with webapi template to work

### ISSUE THREAD

**Issue by mikedld** [CXuesong/JsonRpc.Standard#12]
Not sure if it's the right place, please point me elsewhere if not.

I saw that there's a WebSocket server example here but I'm currently trying to do plain HTTP. I've created a simple test project with a single RPC service having a single exposed method. What I'm doing is basically (with .NET Core 2.2):
1. Run
   ```
   $ dotnet new webapi
   $ dotnet add package CXuesong.JsonRpc.Commons
   $ dotnet add package CXuesong.JsonRpc.AspNetCore
   ```
2. Adjust Startup.cs:
   ```cs
   using JsonRpc.AspNetCore;
   // ...
   public void ConfigureServices(IServiceCollection services)
   {
       // ...
       services.AddJsonRpc(null)
           .Register<MyService>();
   }
   public void Configure(IApplicationBuilder app, IHostingEnvironment env)
   {
       // ...
       app.UseJsonRpc("/api");
   }
   ```
3. Create MyService.cs:
   ```cs
   using System.Threading.Tasks;
   using JsonRpc.Contracts;
   using JsonRpc.Server;

   namespace MyTest
   {
       public class MyService : JsonRpcService
       {
           [JsonRpcMethod]
           public string DoStuff()
           {
               System.Console.WriteLine("Hello from DoStuff");
               return "foobar";
           }
       }
   }
   ```
4. Build/run the service, send request with curl:
   ```
   $ curl -kvvv -H 'Content-Type: application/json' -d '{"jsonrpc":"2.0","method":"DoStuff"}' http://localhost/api
   *   Trying ::1...
   * TCP_NODELAY set
   * Connected to localhost (::1) port 80 (#0)
   > POST /api HTTP/1.1
   > Host: localhost
   > User-Agent: curl/7.64.1
   > Accept: */*
   > Content-Type: application/json
   > Content-Length: 36
   > 
   * upload completely sent off: 36 out of 36 bytes
   < HTTP/1.1 200 OK
   < Date: Sat, 11 May 2019 11:32:19 GMT
   < Server: Kestrel
   < Content-Length: 0
   < 
   * Connection #0 to host localhost left intact
   * Closing connection 0
   ```
5. Debug output on service side shows this upon request:
   ```
   dbug: Microsoft.AspNetCore.Server.Kestrel[1]
         Connection id "0HLMM0PRL0U6K" started.
   info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
         Request starting HTTP/1.1 POST http://localhost/api application/json 36
   dbug: Microsoft.AspNetCore.HttpsPolicy.HstsMiddleware[1]
         The request is insecure. Skipping HSTS header.
   dbug: Microsoft.AspNetCore.Routing.Matching.DfaMatcher[1000]
         No candidates found for the request path '/api'
   dbug: Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware[2]
         Request did not match any endpoints
   dbug: Microsoft.AspNetCore.Server.Kestrel[25]
         Connection id "0HLMM0PRL0U6K", Request id "0HLMM0PRL0U6K:00000001": started reading request body.
   Hello from DoStuff
   dbug: Microsoft.AspNetCore.Server.Kestrel[9]
         Connection id "0HLMM0PRL0U6K" completed keep alive response.
   info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
         Request finished in 0.7945ms 200 
   dbug: Microsoft.AspNetCore.Server.Kestrel[26]
         Connection id "0HLMM0PRL0U6K", Request id "0HLMM0PRL0U6K:00000001": done reading request body.
   dbug: Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets[6]
         Connection id "0HLMM0PRL0U6K" received FIN.
   dbug: Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets[7]
         Connection id "0HLMM0PRL0U6K" sending FIN because: "The client closed the connection."
   dbug: Microsoft.AspNetCore.Server.Kestrel[10]
         Connection id "0HLMM0PRL0U6K" disconnecting.
   dbug: Microsoft.AspNetCore.Server.Kestrel[2]
         Connection id "0HLMM0PRL0U6K" stopped.
   ```

As you could see the request completes successfully but returns empty response. There's also a line printed from `MyService.DoStuff` which means the method gets called just fine. What am I doing wrong, or maybe not doing?

**Comment by CXuesong** [comment]
I think it's because you didn't specify an `id` field, even if it's on HTTP. That's the defintion of a JSON-RPC *request*. If you neglect `id`, it will be a JSON-RPC *notification*.

See https://www.jsonrpc.org/specification#examples for reference.

**Comment by mikedld** [comment]
Hmm, this is interesting. I always thought that whether a particular message is a notification is decided by the service (hence the existence of `IsNotification` in `JsonRpcMethodAttribute`) and not the client (by omitting or including the "id" field). As the description of "id" states at the page you linked to, it's (emphasis mine)

> An identifier established by the Client that MUST contain a String, Number, or NULL value *if included*. If it is not included it is *assumed* to be a notification.

For me this means that there's basically an agreement between a service and a client that notifications don't need to include "id" simply because there's no response and so it just doesn't make sense. Proper methods that do (unlike notifications) have a result, IMHO, need to always return it regardless of whether "id" was passed or not.

I guess what I'm saying is I don't like the wording of that part of the spec... :) Any thoughts?

P.S. Passing "id" indeed leads to the result being returned.

**Comment by mikedld** [comment]
Also from the spec,

> [1] The use of Null as a value for the id member in a Request object is discouraged, because *this specification uses a value of Null for Responses with an unknown id*.

So I guess I'm right in assuming that service is in control :)

**Comment by CXuesong** [comment]
The statement you have quoted:
> If it is not included it is assumed to be a notification.

My understanding is, if there is no `id`, then the message is assumed to be a notification. This is different from `NULL`, however, because the latter case means `id: null` in the request. (Unfortunately, my library does not support this yet.)

**Comment by CXuesong** [comment]
And I think there might be situations where the client is simply not interested in the result returned from the server, nor the client would like to wait for the server to respond. In this case, sending a notification even if the server method is designed to be a JSON-RPC request sounds sensible to me.

**Comment by mikedld** [comment]
There needs to be a single source of truth IMO as to which calls are notifications and which aren't. Since the library provides `IsNotification`, I presume the service is this source. Again, what the spec says is that "all notifications don't have id", it doesn't say that "all messages that don't have id are notifications". Another quote from the spec is that

> The Server MUST reply with the same value in the Response object *if included*. This member is used to correlate the context between the two objects.

It doesn't say that there should be no response if it's not included. The omission of "id" to me means that I just don't need to correlate requests and responses, e.g. because I'm making all the calls synchronously and thus sequentially on the client side. If I want to discard the response, I'm free to do so (e.g. by closing the socket) but the response will still be sent by the service (potentially leading to the error on its side, but since the action is already performed it will act kind of like a notification; which again it really isn't).

**Comment by mikedld** [comment]
Okay, the more I'm reading it the more confusing it gets :) I could see your point, and the original question has been answered (thanks!), so consider this resolved for me. Not closing though since you labeled it "bug" and probably wanted to do something here (?)

**Comment by CXuesong** [comment]
I had been hesitating on whether to put `question` or `bug` on this issue. Because were your issue valid, it would be a bug for sure. But from your reaction, I think it can be misleading so I will put back `question`.
